version: '3.8'

services:
  odoo:
    image: odoo:17.0
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    command: ["sh", "-c", "sleep 10 && /entrypoint.sh odoo"]
    volumes:

      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - wpdb
    volumes:
      - ./wordpress_plugin:/var/www/html/wp-content/plugins/your-plugin

  wpdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - wp-db-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ server

volumes:
  odoo-db-data:
  wp-db-data:

